### ISSUE TITLE
Missing output file(s) `PART_*-cluster_input.tab` expected by process `format_EX_clusters_input`

### ISSUE THREAD

**Issue by evaesquinas** [biocorecrg/ExOrthist#34]
Hello,

I am new using `ExOrthist` and when I was trying to use the test run, the process got stuck in the step "format_EX_clusters_input" giving me the following error that I will add below.

The steps that I have used are the following:
1) git clone https://github.com/biocorecrg/ExOrthist.git
2) I created the following bash script to run the tool on the cluster that I am working on. 
`sbatch script: launc_ExOrthist.sh`

Script:
```
#!/usr/bin/bash
#SBATCH --job-name=ExOrthist
#SBATCH --time=6:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH -o ExOrthist.o
#SBATCH -e ExOrthist.e

#load modules installed on the cluster.
module load nextflow/22.10.4
module load wrf_docker/4.0.3
module load gcccore/system bedtools/2.30.0

NXF_VER=20.04.1 nextflow run main.nf [-with-singularity] > test_log.txt
```

Within the file "test_log.txt", you will see the error and where the process got stuck.

```
--- Pipeline BIOCORE@CRG ExOrthist ---
Started at  2023-03-06T12:57:41.336310991+01:00
Finished at 2023-03-06T13:00:13.668024213+01:00
Time elapsed: 2m 32s
Execution status: failed

executor >  local (27)
[37/467946] process > check_input (1)                [100%] 1 of 1 ✔
[6b/aac78d] process > generate_annotations (mm10)    [100%] 3 of 3 ✔
[1c/0ff779] process > split_clusters_by_species_p... [100%] 1 of 1 ✔
[e6/7b4d54] process > split_clusters_in_chunks (h... [100%] 3 of 3 ✔
[b1/325f35] process > parse_IPA_prot_aln (hg38-mm... [100%] 3 of 3 ✔
[92/6fd11d] process > split_EX_pairs_to_realign (1)  [100%] 1 of 1 ✔
[5d/ac9428] process > realign_EX_pairs (1)           [100%] 3 of 3 ✔
[a9/b63272] process > merge_PROT_EX_INT_aln_info ... [100%] 3 of 3 ✔
[0d/f574e3] process > score_EX_matches (bosTau9-m... [100%] 3 of 3 ✔
[15/812096] process > filter_and_select_best_EX_m... [100%] 3 of 3 ✔
[b7/1f5bea] process > join_filtered_EX_matches       [100%] 1 of 1 ✔
[eb/da6b9b] process > collapse_overlapping_matches   [100%] 1 of 1 ✔
[ac/d564c5] process > format_EX_clusters_input       [100%] 1 of 1, failed: 1 ✘
[-        ] process > cluster_EXs                    -
[-        ] process > format_EX_clusters_output      -
[-        ] process > recluster_genes_by_species_... -
[-        ] process > recluster_EXs_by_species_pair  -
Error executing process > 'format_EX_clusters_input'

Caused by:
  Missing output file(s) `PART_*-cluster_input.tab` expected by process `format_EX_clusters_input`

Command executed:

  if [ `echo hg38_mm10_bosTau9.tab | grep ".gz"` ]; then
      zcat hg38_mm10_bosTau9.tab > cluster_file
      D1_format_EX_clusters_input.pl cluster_file filtered_best_scored_EX_matches_by_targetgene-NoOverlap.tab 500
      rm cluster_file
   else
      D1_format_EX_clusters_input.pl hg38_mm10_bosTau9.tab filtered_best_scored_EX_matches_by_targetgene-NoOverlap.tab 500
   fi

Command exit status:
  0

Command output:
  (empty)

Command error:
  Number of parts:	0

Work dir:
  /mnt/lustre/scratch/nlsas/home/usc/gr/eer/Tools/ExOrthist/work/ac/d564c5749ec19aa2fde8d93130e432

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

I did not change any parameter, path, etc from the config files. In fact, this is the header of the file:
```
N E X T F L O W  ~  version 22.10.4
Launching `main.nf` [small_monod] DSL1 - revision: 8e66712e81


╔╦╗┬ ┬┌─┐  ╔═╗─┐ ┬╔═╗┬─┐┌┬┐┬ ┬┬┌─┐┌┬┐
 ║ ├─┤├┤   ║╣ ┌┴┬┘║ ║├┬┘ │ ├─┤│└─┐ │ 
 ╩ ┴ ┴└─┘  ╚═╝┴ └─╚═╝┴└─ ┴ ┴ ┴┴└─┘ ┴ 

==============================================================================
annotations (GTF files)          : /mnt/lustre/scratch/nlsas/home/usc/gr/eer/Tools/ExOrthist/test/GTF/*_annot-subsetted.gtf.gz
genomes (fasta files)            : /mnt/lustre/scratch/nlsas/home/usc/gr/eer/Tools/ExOrthist/test/GENOMES/*_gDNA-subsetted.fasta.gz
cluster file (txt files)         : /mnt/lustre/scratch/nlsas/home/usc/gr/eer/Tools/ExOrthist/test/hg38_mm10_bosTau9.tab
pairwise evo distances           : /mnt/lustre/scratch/nlsas/home/usc/gr/eer/Tools/ExOrthist/test/evodists.txt
long distance parameters         : 2,0.10,0.40,0.15
medium distance parameters       : 2,0.30,0.60,0.20
short distance parameters        : 2,0.50,0.60,0.25
pre-computed alignments		 : 
alignment number		 : 1000
orthogroup number		 : 500
extraexons (e.g. from VastDB)    : 
bona fide orthologous exon pairs  : 
orthopairs                       : 
output (output folder)           : /mnt/lustre/scratch/nlsas/home/usc/gr/eer/Tools/ExOrthist/output_test
email for notification           : yourmail@yourdomain
```

On the other hand, I have to say that I loaded `bedtools` and I also downloaded `liftOver` (although I am not calling this one for this step).

Could it be possible that I am getting those errors because of the version that I am using of nextflow, singularity, etc.? Or could it be something else that I am missing?

Look forward to your reply,

Thanks very much in advance

Regards

**Comment by fedemantica** [comment]
Hi Eva! Can you please pull the last modifications we made and see if they work for you? Hopefully we fixed the problem!
Thanks :)

**Comment by evaesquinas** [comment]
Hi, thanks very much for your reply!

I cloned the repository from scratch (just in case) and since I saw that you changed one command in the readme file, I modified it too (I removed "NXF_VER=20.04.1"). However, I still have the same problem... it got stuck in the same step.

I thought that maybe was because I was loading to many modules on the cluster... but I kept nextflow (and when this is loaded singularity is also loaded) but it seems that it is not the problem..
```
module load nextflow/22.10.4
jdk/17.0.2 loaded
squashfs/4.3 loaded
singularity/3.6.3 loaded
nextflow/22.10.4 loaded
```
